# Generated by Django 4.2.1 on 2023-06-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.TextField(default=0, max_length=24),
            preserve_default=False,
        ),
    ]
