# Generated by Django 4.2.1 on 2023-06-05 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_listing_id_alter_bid_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='currentBid',
        ),
    ]
