# Generated by Django 4.2.1 on 2023-06-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_category_remove_listing_category_listing_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
